### ISSUE TITLE
1.15.2 support

### ISSUE THREAD

**Issue by capuano1** [DxsSucuk/TrollV4#1]
Hello, I really don't know if you're still working on it, or if it should work, but when I tried to use TrollV4 on my 1.15.2 server it gave me this error: https://pastebin.com/UrZiTahP, and it doesn't really activate the plugin because of it (the plugin appears red on the plugin list).

**Comment by DxsSucuk** [comment]
Do you have LibsDisguises and ProtocolLibs on your Server?

**Comment by DxsSucuk** [comment]
This Bug should be fixed in 4.3.1
