### ISSUE TITLE
Add Italian language

### ISSUE THREAD

**Issue by JamesTheFlash22** [DxsSucuk/TrollV4#15]
I can add the It language, do u want?

**Comment by DxsSucuk** [comment]
Late response, If you did like sure!
But its gonna take a bit before I make a new System for the Language.

**Comment by DxsSucuk** [comment]
Well "take a bit" was a lie. I finished the new language system just make a new file in the languages folder called "it_it.yml" and edit it.

**Comment by JamesTheFlash22** [comment]
> Well "take a bit" was a lie. I finished the new language system just make a new file in the languages folder called "it_it.yml" and edit it.

Ok

**Comment by JamesTheFlash22** [comment]
I made PR, good luck also with ree6

**Comment by DxsSucuk** [comment]
Thank you very much, got it merged!
