### ISSUE TITLE
Newest version

### ISSUE THREAD

**Issue by ghost** [DxsSucuk/TrollV4#16]
Console output:

05.08 18:00:06 [Server] WARN [TrollV4] TrollV4 has a update!
05.08 18:00:06 [Server] WARN [TrollV4] New Version: 4.5.19
05.08 18:00:06 [Server] WARN [TrollV4] Your Version: 4.5.20
05.08 18:00:06 [Server] WARN [TrollV4] Download here: https://www.spigotmc.org/resources/67318/updates

**Comment by ghost** [comment]
Ah thats not the only error:

05.08 18:02:34 [Server] ERROR Command exception: /trollv4
05.08 18:02:34 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'trollv4' in plugin TrollV4 v4.5.20
05.08 18:02:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
05.08 18:02:34 [Server] INFO at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
05.08 18:02:34 [Server] INFO at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
05.08 18:02:34 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
05.08 18:02:34 [Server] INFO Caused by: java.lang.ExceptionInInitializerError
05.08 18:02:34 [Server] INFO at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.SkullUtils.<clinit>(SkullUtils.java:83) ~[TrollV4.jar:?]
05.08 18:02:34 [Server] INFO at TrollV4.jar/de.presti.trollv4.invs.SetItems.buildSkull(SetItems.java:39) ~[TrollV4.jar:?]
05.08 18:02:34 [Server] INFO at TrollV4.jar/de.presti.trollv4.invs.InvManager.choicePlayer(InvManager.java:497) ~[TrollV4.jar:?]
05.08 18:02:34 [Server] INFO at TrollV4.jar/de.presti.trollv4.cmd.Haupt.onCommand(Haupt.java:115) ~[TrollV4.jar:?]
05.08 18:02:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
05.08 18:02:34 [Server] INFO ... 26 more
05.08 18:02:34 [Server] INFO Caused by: java.lang.IllegalStateException: Cannot parse server version: "1.21-R0.1-SNAPSHOT"
05.08 18:02:34 [Server] INFO at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.ReflectionUtils.<clinit>(ReflectionUtils.java:173) ~[TrollV4.jar:?]
05.08 18:02:34 [Server] INFO at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.SkullUtils.<clinit>(SkullUtils.java:83) ~[TrollV4.jar:?]
05.08 18:02:34 [Server] INFO at TrollV4.jar/de.presti.trollv4.invs.SetItems.buildSkull(SetItems.java:39) ~[TrollV4.jar:?]
05.08 18:02:34 [Server] INFO at TrollV4.jar/de.presti.trollv4.invs.InvManager.choicePlayer(InvManager.java:497) ~[TrollV4.jar:?]
05.08 18:02:34 [Server] INFO at TrollV4.jar/de.presti.trollv4.cmd.Haupt.onCommand(Haupt.java:115) ~[TrollV4.jar:?]
05.08 18:02:34 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
05.08 18:02:34 [Server] INFO ... 26 more

**Comment by DxsSucuk** [comment]
The missmatched version output is normal it takes time for the spigot api to update its version. For the other exception, I will need to hope that there is a update for Cryptomorins XSeries API otherwise gotta wait for that one to release.

**Comment by DxsSucuk** [comment]
Should be fixed in the latest version.
