### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Paraxdev** [DxsSucuk/TrollV4#2]
hello. I also have an troll plugin and i use your packet class. I linked you and everything..
Im asking since i only now saw an copyright text.
So i would nicely ask if it is ok to use it?
If not i can just remove it ^^

**Comment by DxsSucuk** [comment]
If you give me credits for the class you can use it how ever you want :)

**Comment by Xapu1337** [comment]
@DxsSucuk also wouldn't an switch case inside:
https://github.com/DxsSucuk/TrollV4/blob/master/trollv4/src/de/presti/trollv4/listener/GuiListener.java
be cleaner? i mean... that code is kinda hard to look at 😄

**Comment by DxsSucuk** [comment]
It would be cleaner but i dont have the time for it right now

**Comment by Xapu1337** [comment]
i made an fork, if i have some time im going to make it with an case.

**Comment by DxsSucuk** [comment]
kk
