### ISSUE TITLE
Your plugin misgendered me <_<

### ISSUE THREAD

**Issue by LiEnby** [DxsSucuk/TrollV4#4]
you hard code he/him male pronouns in multiple places; when the person in question may or may not be a guy and use he/him pronouns;

https://github.com/DxsSucuk/TrollV4/blob/1baca4d8a020860f68cce4bb23dea91d73ac93a7/trollv4/src/main/java/de/presti/trollv4/config/Language.java#L271

https://github.com/DxsSucuk/TrollV4/blob/1baca4d8a020860f68cce4bb23dea91d73ac93a7/trollv4/src/main/java/de/presti/trollv4/config/Language.java#L272

https://github.com/DxsSucuk/TrollV4/blob/1baca4d8a020860f68cce4bb23dea91d73ac93a7/trollv4/src/main/java/de/presti/trollv4/config/Language.java#L276

https://github.com/DxsSucuk/TrollV4/blob/1baca4d8a020860f68cce4bb23dea91d73ac93a7/trollv4/src/main/java/de/presti/trollv4/config/Language.java#L277

use like "they/them/their" or maybe rewrite it so like it doesn't require third person pronouns; for example 

"The User &c[PLAYER] &2now sees only TnT in his World!" could be written "The User &c[PLAYER] &2now sees only TnT in the World!" and would still make sense;

**Comment by DxsSucuk** [comment]
Didn't see this Issue since I stopped activily working on this Project, well sorry if it offended you. But there is a custom language option for a reason, you can modify all the messages based on the english language file in your config.

**Comment by Solastis** [comment]
😑😵‍💫😴

**Comment by DxsSucuk** [comment]
Closing since there is no actual reason to keep it open.

**Comment by Solastis** [comment]
soft
